### ISSUE TITLE
This is incorrect.

### ISSUE THREAD

**Issue by wmichelin** [matthewbdaly/laravel-etag-middleware#5]
I should be able to make a `HEAD` request to the same URL and get the same ETag as I would making a `GET` request.

**Comment by matthewbdaly** [comment]
Should be straightforward enough to fix - just a matter of changing the if statement to catch `GET` and `HEAD` requests, and maybe changing the request to a `GET` so it will return the correct content for generating the MD5. If you want to submit a pull request I'll pull it in, otherwise I'll take a look when I can.

**Comment by matthewbdaly** [comment]
This has now been implemented and is available in the new release.
